# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v2-node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm run lint
  build:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm run build
      - save_cache:
          key: v2-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - docs
  test-unit:
    docker:
      - image: circleci/node:8.7-browsers
    parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: circleci tests glob "test/unit/**/*.js" "test/unit/*.js" | circleci tests split | xargs npm run ci-unit --
  test-e2e:
    docker:
      - image: circleci/node:8.7-browsers
    parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run doc -- --port 8089 & (circleci tests glob "test/e2e/**/*.js" "test/e2e/*.js" | circleci tests split | xargs npm run ci-e2e -- -c 2)
  coverage:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run doc -- --port 8089 & npm run ci-cover
      - save_cache:
          key: v2-coverage-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .nyc_output
  codecov:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v2-coverage-output-{{ .Environment.CIRCLE_SHA1 }}
      - run: sudo npm install -g codecov
      - run: npm run codecov-report && codecov

workflows:
  version: 2
  lint_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test-unit:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - coverage:
          requires:
            - test-unit
            - test-e2e
      - codecov:
          requires:
            - coverage